### ISSUE TITLE
999 call to action on condition page is at bottom in portrait mode on phone/tablet

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsalpha/connecting-to-services-hack-day#106]

**Comment by st3v3nhunt** [comment]
This is by design?
https://beta.nhs.uk/symptoms/stomach-ache

**Comment by neilbmclaughlin** [comment]
I'm guessing it is but just logging it as an outcome from our internal user testing.

**Comment by neilbmclaughlin** [comment]
I think that the rashes prototype has the 999 call to action at the top.

**Comment by neilbmclaughlin** [comment]
Just checked this on the beta site it is the same. Red call to action at the top for rashes and at the bottom for stomach ache. It may be intentional.
Left feedback on the beta site high lighting this and closing the issue here.

/cc @Demotive @teneightfive

**Comment by teneightfive** [comment]
@neilbmclaughlin Sorry, just caught up on this. Yep, this is intentional behaviour. We have 2 different layouts that we can choose from which stacks the emergency info box either at the top or at the bottom on smaller devices. On wider devices it will still always appear on the right hand side.

The reason for this is down to the importance on that emergency information for that condition/symptom. With rashes we want the user to read through this information early as it can be quite serious, whereas with stomach ache we are testing how it works for users if that information comes after the main content. In theory that panel could appear anywhere as we start to test more conditions and symptoms. So it's more of a content first design at the moment rather than always sticking strictly to one pattern.
